export const ENUM_NOTIFICATION_TYPE = {
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  SHIFT_REQUESTED: 'SHIFT_REQUESTED',
  SHIFT_ACCEPTED: 'SHIFT_ACCEPTED',
  SHIFT_REJECTED: 'SHIFT_REJECTED',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  TIP_RECEIVED: 'TIP_RECEIVED',
  JOB_ASSIGNED: 'JOB_ASSIGNED',
  JOB_CANCELLED: 'JOB_CANCELLED',
  REVIEW_RECEIVED: 'REVIEW_RECEIVED',
  JOB_CREATED: 'JOB_CREATED',
};
export const NOTIFICATION_ACTION = {
  VIEW: 'VIEW', // go to specific item (order details, shift details)
  LIST: 'LIST', // go to list page (my orders, my shifts)
  ACCEPT: 'ACCEPT', // action type (e.g., accept shift)
};

export const NOTIFICATION_ENTITY = {
  ORDER: 'ORDER',
  SHIFT: 'SHIFT',
  PAYMENT: 'PAYMENT',
  USER: 'USER',
  CAMPAIGN: 'CAMPAIGN',
  REVIEW: 'REVIEW',
  JOB: 'JOB',
} as const;

export type NOTIFICATION_ENTITY_TYPE =
  (typeof NOTIFICATION_ENTITY)[keyof typeof NOTIFICATION_ENTITY];
